## Summary of script
## ----------------
## This script creates a special "matrix" object that can cache its inverse,
## inverts a matrix x, caches the inverse and retreives the cached version
## if asked to invert the matrix again

## The execution is by  "a<-makeCacheMatrix(x)"  then "cacheSolve(a)"


## Function "makeCacheMatrix"
## -------------------------
## The function makeCacheMatrix" creates a special "matrix" object that can cache its inverse

## makeCacheMatrix creates a list containing functions as follows

   ## set -  this function stores the matrix x
   ## get - this function retrieves the stored matrix x
   ## setmatrix -  this function stores the inverse of the matrix x
   ## getmatrix - this function retrives the stored inverse of the matrix x

## These functions are then used by the fuction cacheSolve 
## cacheSolve computes  the inverse of the matrix x
## or if it has previously been computed retrieves the previous solution

## The list containing the functions generated by makeCacheMatrix is the input to cacheSolve
## i.e execution is by  "a<-makeCacheMatrix(x)"  then "cacheSolve(a)"


makeCacheMatrix <- function(x = matrix()) {
  
    matinv<-NULL
    set<-function(y){
      x<<-y
      matinv<<-NULL
    }
    get<-function() x
    setmatrix<-function(solve) matinv<<- solve
    getmatrix<-function() matinv
    list(set=set, get=get, setmatrix=setmatrix, getmatrix=getmatrix)
  }
  
## Function "cacheSolve"
## ---------------------
## The function "cacheSolve" computes the inverse of the matrix x input to makeCacheMatrix above

## The solve function is used to compute the inverse
## The matrix used must be an invertible matrix

## The Inverse is cached using the function "setmatrix" defined above
## If the matrix has been previously inverted then the inverse is retreived
## using the function "getmatrix" also defined above

## The functions "get", "setmatrix"and "getmatrix" are defined
## in the list made by the function "makeCacheMatrix" above
## This list is the Arguement for the function "cacheSolve"


cacheSolve <- function(fdefs,...){
       
  ## Returns a matrix that is the inverse of 'x' in the above
  ## uses the functions "get", "setmatrix"and "getmatrix" defined above 
  ## and pased to "cacheSolve" in the list output by "makeCacheMatrix"
  
    matinv<-fdefs$getmatrix()        # retrieves the inverse of matrix from cache
                                     # using "getmatrix"
    
    if(!is.null(matinv)){            # tests if inverse exists(is not NULL)
      message("getting cached data") 
      return(matinv)                 # returns cached inverse if it exists
    }
                                     # Otherwise i.e when no inverse is cached
    
    matrix<-fdefs$get()              # retreives the matrix (using "get")
    matinv<-solve(matrix, ...)       # inverts the matrix 
    fdefs$setmatrix(matinv)          # caches the inverse (using "setmatrix")
    matinv                   
  }
